In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [8]:
x_train

    age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
22   71  Female   98.0  Strong    Kolkata
62   56  Female  104.0  Strong  Bangalore
33   26  Female   98.0    Mild    Kolkata
93   27    Male  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
68   54  Female  104.0  Strong    Kolkata
99   10  Female   98.0  Strong    Kolkata
26   19  Female  100.0    Mild    Kolkata
6    14    Male  101.0  Strong  Bangalore
38   49  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

# 1. Without column transformer

In [9]:
# for fever column-> simple imputer
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [11]:
# cough->Ordinal  encoding
oe=OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [13]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [14]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [ ]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,X_test_gender_city,X_test_cough),axis=1)

x_train_transformed.shape