In [1]:
import numpy as np
import pandas as pd

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
date.isnull().value_counts

<bound method DataFrame.value_counts of       date  product_id  city_id  orders
0    False       False    False   False
1    False       False    False   False
2    False       False    False   False
3    False       False    False   False
4    False       False    False   False
..     ...         ...      ...     ...
995  False       False    False   False
996  False       False    False   False
997  False       False    False   False
998  False       False    False   False
999  False       False    False   False

[1000 rows x 4 columns]>

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with dates

In [8]:
date['date']=pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

# 1. extract year

In [11]:
date['date_year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

# 2. extract month

In [12]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [13]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

# 3. extract days

In [14]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [15]:
date['date_dow']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

# extract time elapses between dates

In [16]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 6, 25, 16, 51, 9, 431558)

In [17]:
today-date['date']

0     2389 days 16:51:09.431558
1     2871 days 16:51:09.431558
2     2802 days 16:51:09.431558
3     2504 days 16:51:09.431558
4     2727 days 16:51:09.431558
                 ...
995   2817 days 16:51:09.431558
996   2758 days 16:51:09.431558
997   2606 days 16:51:09.431558
998   2671 days 16:51:09.431558
999   2445 days 16:51:09.431558
Name: date, Length: 1000, dtype: timedelta64[ns]

In [18]:
# months passed

In [20]:
np.round((today-date['date'])/np.timedelta64(1,'m'),0)

0      3441171.0
1      4135251.0
2      4035891.0
3      3606771.0
4      3927891.0
         ...
995    4057491.0
996    3972531.0
997    3753651.0
998    3847251.0
999    3521811.0
Name: date, Length: 1000, dtype: float64